/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as EstudioRouteImport } from './routes/estudio'
import { Route as AuthenticatedEventosRouteImport } from './routes/_authenticated/eventos'
import { Route as ApiGenerateFlipRouteImport } from './routes/api/generate-flip'
import { Route as AuthenticatedEventoEventIdRouteImport } from './routes/_authenticated/evento.$eventId'
import { Route as AuthenticatedKioscoEventIdRouteImport } from './routes/_authenticated/kiosco.$eventId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudioRoute = EstudioRouteImport.update({
  id: '/estudio',
  path: '/estudio',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEventosRoute = AuthenticatedEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiGenerateFlipRoute = ApiGenerateFlipRouteImport.update({
  id: '/api/generate-flip',
  path: '/api/generate-flip',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEventoEventIdRoute =
  AuthenticatedEventoEventIdRouteImport.update({
    id: '/evento/$eventId',
    path: '/evento/$eventId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKioscoEventIdRoute =
  AuthenticatedKioscoEventIdRouteImport.update({
    id: '/kiosco/$eventId',
    path: '/kiosco/$eventId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/estudio': typeof EstudioRoute
  '/eventos': typeof AuthenticatedEventosRoute
  '/api/generate-flip': typeof ApiGenerateFlipRoute
  '/evento/$eventId': typeof AuthenticatedEventoEventIdRoute
  '/kiosco/$eventId': typeof AuthenticatedKioscoEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/estudio': typeof EstudioRoute
  '/eventos': typeof AuthenticatedEventosRoute
  '/api/generate-flip': typeof ApiGenerateFlipRoute
  '/evento/$eventId': typeof AuthenticatedEventoEventIdRoute
  '/kiosco/$eventId': typeof AuthenticatedKioscoEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/estudio': typeof EstudioRoute
  '/_authenticated/eventos': typeof AuthenticatedEventosRoute
  '/api/generate-flip': typeof ApiGenerateFlipRoute
  '/_authenticated/evento/$eventId': typeof AuthenticatedEventoEventIdRoute
  '/_authenticated/kiosco/$eventId': typeof AuthenticatedKioscoEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/estudio'
    | '/eventos'
    | '/api/generate-flip'
    | '/evento/$eventId'
    | '/kiosco/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/estudio'
    | '/eventos'
    | '/api/generate-flip'
    | '/evento/$eventId'
    | '/kiosco/$eventId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/estudio'
    | '/_authenticated/eventos'
    | '/api/generate-flip'
    | '/_authenticated/evento/$eventId'
    | '/_authenticated/kiosco/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EstudioRoute: typeof EstudioRoute
  ApiGenerateFlipRoute: typeof ApiGenerateFlipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudio': {
      id: '/estudio'
      path: '/estudio'
      fullPath: '/estudio'
      preLoaderRoute: typeof EstudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/eventos': {
      id: '/_authenticated/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof AuthenticatedEventosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/generate-flip': {
      id: '/api/generate-flip'
      path: '/api/generate-flip'
      fullPath: '/api/generate-flip'
      preLoaderRoute: typeof ApiGenerateFlipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/evento/$eventId': {
      id: '/_authenticated/evento/$eventId'
      path: '/evento/$eventId'
      fullPath: '/evento/$eventId'
      preLoaderRoute: typeof AuthenticatedEventoEventIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kiosco/$eventId': {
      id: '/_authenticated/kiosco/$eventId'
      path: '/kiosco/$eventId'
      fullPath: '/kiosco/$eventId'
      preLoaderRoute: typeof AuthenticatedKioscoEventIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEventosRoute: typeof AuthenticatedEventosRoute
  AuthenticatedEventoEventIdRoute: typeof AuthenticatedEventoEventIdRoute
  AuthenticatedKioscoEventIdRoute: typeof AuthenticatedKioscoEventIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEventosRoute: AuthenticatedEventosRoute,
  AuthenticatedEventoEventIdRoute: AuthenticatedEventoEventIdRoute,
  AuthenticatedKioscoEventIdRoute: AuthenticatedKioscoEventIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EstudioRoute: EstudioRoute,
  ApiGenerateFlipRoute: ApiGenerateFlipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
